# Generated by Django 5.2.4 on 2025-07-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
    ]
