# Generated by Django 5.1.4 on 2025-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_employeerole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=100)),
                ('blog_details', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
