# Generated by Django 5.2.4 on 2025-07-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_employeerole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
