# Generated by Django 5.2.4 on 2025-08-02 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_permission_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('inventory', 'Inventory Manager'), ('orders', 'Order Handler'), ('sales', 'Sales Manager')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.role'),
        ),
    ]
