# Generated by Django 5.2.4 on 2025-08-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_role_alter_rolepermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.role'),
        ),
    ]
