# Generated by Django 5.2.4 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_employeerole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
    ]
