# Generated by Django 5.2.4 on 2025-08-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_employeerole_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
