# Generated by Django 5.2.4 on 2025-08-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_employeerole_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
