# Generated by Django 5.2.4 on 2025-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Silver', 'Silver')], max_length=100),
        ),
    ]
