# Generated by Django 5.1.4 on 2025-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Silver', 'Silver'), ('pearl', 'Pearl')], max_length=100),
        ),
    ]
